#!/usr/bin/env bash
# Cloud Agent start phase: per-boot reconciliation of the local database.
# Starts PostgreSQL, ensures the role/database exist, writes a local .env if
# missing, and applies migrations + seed data. Idempotent and safe to re-run.
set -euo pipefail

PG_VER=16
PG_CLUSTER=main

# Resolve repo root (this script lives in <repo>/.cursor/).
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# --- Start the PostgreSQL cluster (idempotent; ignores "already running"). ---
sudo pg_ctlcluster "$PG_VER" "$PG_CLUSTER" start 2>/dev/null || true

# --- Wait for readiness. ---
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q; then break; fi
  sleep 1
done
sudo -u postgres pg_isready

# --- Ensure the postgres password and the wakemark database exist. ---
sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';" >/dev/null
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='wakemark'" | grep -q 1; then
  sudo -u postgres psql -c "CREATE DATABASE wakemark;" >/dev/null
fi

# --- Generate a local development .env if one is not already present. ---
if [ ! -f .env ]; then
  SECRET="$(openssl rand -base64 32)"
  cat > .env <<EOF
# Local development environment (generated by .cursor/start.sh)
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_PRICING_PATH="/#pricing"
NEXT_PUBLIC_LOCALE_DETECTION=false
NEXT_PUBLIC_OPTIMIZED_IMAGES=false
NEXT_PUBLIC_LOGIN_MODE=dialog
NEXT_PUBLIC_COOKIE_CONSENT_ENABLED="false"
NEXT_PUBLIC_USER_SOURCE_TRACKING_ENABLED="true"
NEXT_PUBLIC_RATE_LIMIT_ENABLED="false"
NEXT_PUBLIC_EMAIL_NORMALIZATION_ENABLED="false"

DATABASE_URL="postgresql://postgres:postgres@localhost:5432/wakemark"

BETTER_AUTH_SECRET="$SECRET"

LOG_LEVEL=info
EOF
  echo "start.sh: wrote local .env"
fi

# --- Apply migrations + seed pricing data (idempotent). ---
pnpm db:migrate
pnpm db:seed

echo "start.sh: database ready"
